name: myenv  # 생성할 conda 환경 이름
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter    # .ipynb 실행을 위해 필수
  - pandas     # 예시 라이브러리
  - numpy      # 예시 라이브러리
  # ... 필요한 다른 라이브러리 추가 ...